// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

let supabaseClient: any;

try {
  // Try to create the Supabase client
  supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'mtaa-loop-auth-token',
      flowType: 'pkce',
    }
  });
} catch (error) {
  // If Supabase client creation fails, use a simple fallback
  supabaseClient = {
    from: () => ({
      select: () => ({
        eq: () => ({
          single: () => Promise.resolve({
            data: null,
            error: {
              message: 'Supabase client initialization failed',
              code: 'CLIENT_INIT_FAILED'
            }
          })
        })
      })
    }),
    auth: {
      signIn: () => Promise.resolve({
        data: { user: null, session: null },
        error: { message: 'Supabase client initialization failed', code: 'CLIENT_INIT_FAILED' }
      }),
      signUp: () => Promise.resolve({
        data: { user: null, session: null },
        error: { message: 'Supabase client initialization failed', code: 'CLIENT_INIT_FAILED' }
      }),
      signOut: () => Promise.resolve({
        data: {},
        error: { message: 'Supabase client initialization failed', code: 'CLIENT_INIT_FAILED' }
      }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => {}
          }
        }
      })
    },
    functions: {
      invoke: () => Promise.resolve({
        data: null,
        error: { message: 'Supabase client initialization failed', code: 'CLIENT_INIT_FAILED' }
      })
    },
    channel: () => ({
      on: () => ({
        on: () => ({
          subscribe: () => Promise.resolve({
            subscription: {
              unsubscribe: () => Promise.resolve()
            }
          })
        })
      }),
      subscribe: () => Promise.resolve(),
      send: () => Promise.resolve(),
      unsubscribe: () => Promise.resolve()
    }),
    removeChannel: () => Promise.resolve()
  };
}

export const supabase = supabaseClient;
